=head1 NAME

Analytic - Context for Annotation of Analytical Syntax in the TrEd Environment


=head1 REVISION

    $Revision: 708 $       $Date: 2008-09-16 01:16:46 +0200 (Tue, 16 Sep 2008) $


=head1 DESCRIPTION

For reference, see the list of Analytic macros and key-bindings in the User-defined menu item in TrEd.




=head1 BINDINGS

=over

=item '1'

Arabic: Suffix Parallel C<assign_parallel>

=item '2'

Arabic: Suffix Paren C<assign_paren>

=item '3'

Arabic: Suffix ArabFa C<assign_arabfa>

=item '4'

Arabic: Suffix ArabSpec C<assign_arabspec>

=item '5'

Arabic: Suffix ArabClause C<assign_arabclause>

=item 'ALT+Down'

Annotate: Current node to either side brother if unique C<thisToEitherBrother>

=item 'ALT+Left'

Annotate: Current node to brother on the left C<thisToRBrother>

=item 'ALT+Right'

Annotate: Current node to brother on the right C<thisToLBrother>

=item 'ALT+SHIFT+Down'

Annotate: Current node exchanged with parent C<SwapNodesUp>

=item 'ALT+SHIFT+Left'

Annotate: Current node to uncle on the left C<thisToParentRBrother>

=item 'ALT+SHIFT+Right'

Annotate: Current node to uncle on the right C<thisToParentLBrother>

=item 'ALT+SHIFT+Up'

Annotate: Current node to the root C<thisToRoot>

=item 'ALT+Up'

Annotate: Current node up one level to grandparent C<thisToParent>

=item 'BackSpace'

Annotate: Undo recent annotation action C<invoke_undo>

=item 'CTRL+ALT+1'

Action: Edit MorphoTrees File C<open_level_first>

=item 'CTRL+ALT+2'

Action: Edit Analytic File C<open_level_second>

=item 'CTRL+ALT+3'

Action: Edit DeepLevels File C<open_level_third>

=item 'CTRL+ALT+Down'

Annotate: Current node to inferior clause head C<thisToInferClauseHead>

=item 'CTRL+ALT+Left'

Annotate: Current node to following clause head C<thisToRightClauseHead>

=item 'CTRL+ALT+Right'

Annotate: Current node to preceeding clause head C<thisToLeftClauseHead>

=item 'CTRL+ALT+Up'

Annotate: Current node to superior clause head C<thisToSuperClauseHead>

=item 'CTRL+ALT+equal'

Action: Synchronize Annotations C<synchronize_file>

=item 'CTRL+Down'

Move to the Inferior Clause Head C<infer_clause_head>

=item 'CTRL+E'

I<not in the menu> C<afun_AuxE_Pa>

=item 'CTRL+End'

Move to Leftmost Descendant C<move_deep_end>

=item 'CTRL+Home'

Move to Rightmost Descendant C<move_deep_home>

=item 'CTRL+Left'

Move to the Following Clause Head C<next_clause_head>

=item 'CTRL+M'

I<not in the menu> C<afun_AuxM_Pa>

=item 'CTRL+Return'

ThisAddress() to Clipboard C<ThisAddressClipBoard>

=item 'CTRL+Right'

Move to the Preceeding Clause Head C<prev_clause_head>

=item 'CTRL+SHIFT+Down'

Move Down to Fork C<move_to_fork>

=item 'CTRL+SHIFT+F10'

Arabic: Request auto afun for current subtree C<request_auto_afun_subtree>

=item 'CTRL+SHIFT+F2'

Arabic: Parse the current sentence and build a tree C<padt_auto_parse_tree>

=item 'CTRL+SHIFT+F8'

Arabic: Toggle request mode for auto afuns C<hooks_request_mode>

=item 'CTRL+SHIFT+F9'

Arabic: Request auto afun for current node C<request_auto_afun_node>

=item 'CTRL+SHIFT+Up'

Move Up to Root C<move_to_root>

=item 'CTRL+T'

I<not in the menu> C<afun_Ante_Pa>

=item 'CTRL+Up'

Move to the Superior Clause Head C<super_clause_head>

=item 'CTRL+X'

I<not in the menu> C<afun_ExD_Pa>

=item 'CTRL+e'

I<not in the menu> C<afun_AuxE_Co>

=item 'CTRL+equal'

Toggle Children Hiding C<tree_hide_mode>

=item 'CTRL+m'

I<not in the menu> C<afun_AuxM_Co>

=item 'CTRL+minus'

Hide Children Subtrees C<hide_children>

=item 'CTRL+plus'

Unhide Children Recursively C<unhide_subtree>

=item 'CTRL+question'

Arabic: Unset and request auto afun C<unset_request_afun>

=item 'CTRL+space'

Arabic: Accept auto-assigned annotation C<accept_auto_afun>

=item 'CTRL+t'

I<not in the menu> C<afun_Ante_Co>

=item 'CTRL+underscore'

Hide This Subtree C<hide_this>

=item 'CTRL+x'

I<not in the menu> C<afun_ExD_Co>

=item 'E'

I<not in the menu> C<afun_AuxE_Ap>

=item 'End'

Move to Last Word C<move_word_end>

=item 'F8'

Display: Show / hide morphological tags C<default_ar_attrs>

=item 'Home'

Move to First Word C<move_word_home>

=item 'M'

I<not in the menu> C<afun_AuxM_Ap>

=item 'SHIFT+End'

Move to Last Paragraph C<move_par_end>

=item 'SHIFT+Home'

Move to First Paragraph C<move_par_home>

=item 'SHIFT+Next'

Move to Next Paragraph C<move_to_next_paragraph>

=item 'SHIFT+Prior'

Move to Prev Paragraph C<move_to_prev_paragraph>

=item 'SHIFT+space'

Annotate: Move to previous ??? C<annotate_previous>

=item 'T'

I<not in the menu> C<afun_Ante_Ap>

=item 'X'

I<not in the menu> C<afun_ExD_Ap>

=item 'e'

Arabic: Assign afun AuxE C<afun_AuxE>

=item 'exclam'

Annotate: Edit annotator's comment C<edit_comment>

=item 'm'

Arabic: Assign afun AuxM C<afun_AuxM>

=item 'question'

Arabic: Unset afun to ??? C<unset_afun>

=item 'space'

Annotate: Move to following ??? C<annotate_following>

=item 't'

Arabic: Assign afun Ante C<afun_Ante>

=item 'x'

Arabic: Assign afun ExD C<afun_ExD>

=back

=head1 SEE ALSO

TrEd Tree Editor L<http://ufal.mff.cuni.cz/~pajas/tred/>

Prague Arabic Dependency Treebank L<http://ufal.mff.cuni.cz/padt/online/>


=head1 AUTHOR

Otakar Smrz, L<http://ufal.mff.cuni.cz/~smrz/>

    eval { 'E<lt>' . ( join '.', qw 'otakar smrz' ) . "\x40" . ( join '.', qw 'mff cuni cz' ) . 'E<gt>' }

Perl is also designed to make the easy jobs not that easy ;)


=head1 COPYRIGHT AND LICENSE

Copyright 2004-2008 by Otakar Smrz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


