=head1 NAME

ElixirFM - Context for Annotation of the ElixirFM Lexicon in the TrEd Environment


=head1 REVISION

    $Revision: 838 $       $Date: 2009-04-09 01:14:18 +0200 (Thu, 09 Apr 2009) $


=head1 DESCRIPTION

ElixirFM ...




=head1 BINDINGS

=over

=item 'BackSpace'

Undo Action C<invoke_undo>

=item 'CTRL+A'

Change Entity Adj C<change_entity_A>

=item 'CTRL+ALT+1'

Action: Edit MorphoTrees File C<open_level_first>

=item 'CTRL+ALT+2'

Action: Edit Analytic File C<open_level_second>

=item 'CTRL+ALT+3'

Action: Edit DeepLevels File C<open_level_third>

=item 'CTRL+C'

Change Entity Conj C<change_entity_C>

=item 'CTRL+D'

Change Entity Adv C<change_entity_D>

=item 'CTRL+End'

Move to Last Entry C<move_next_end>

=item 'CTRL+F'

Change Entity Part C<change_entity_F>

=item 'CTRL+G'

Change Entity Grph C<change_entity_G>

=item 'CTRL+Home'

Move to First Entry C<move_next_home>

=item 'CTRL+I'

Change Entity Intj C<change_entity_I>

=item 'CTRL+N'

Change Entity Noun C<change_entity_N>

=item 'CTRL+P'

Change Entity Prep C<change_entity_P>

=item 'CTRL+Q'

Change Entity Num C<change_entity_Q>

=item 'CTRL+Return'

ThisAddress() to Clipboard C<ThisAddressClipBoard>

=item 'CTRL+S'

Change Entity Pron C<change_entity_S>

=item 'CTRL+SHIFT+Down'

Move Down to Fork C<move_to_fork>

=item 'CTRL+SHIFT+Up'

Move Up to Root C<move_to_root>

=item 'CTRL+V'

Change Entity Verb C<change_entity_V>

=item 'CTRL+X'

Change Entity Xtra C<change_entity_X>

=item 'CTRL+Y'

Change Entity Ynit C<change_entity_Y>

=item 'CTRL+Z'

Change Entity Zero C<change_entity_Z>

=item 'CTRL+c'

Edit: Copy Subtree C<copy_subtree>

=item 'CTRL+d'

Edit: Delete Subtree C<delete_subtree>

=item 'CTRL+e'

New Entry C<new_Entry>

=item 'CTRL+equal'

Hiding Level Reset C<hiding_level_reset>

=item 'CTRL+f'

New Frame C<new_Frame>

=item 'CTRL+l'

Enforce Literal C<enforce_literal>

=item 'CTRL+minus'

Hiding Level Higher C<hiding_level_higher>

=item 'CTRL+n'

New Nest C<new_Nest>

=item 'CTRL+p'

Paradigm Except C<paradigm_except>

=item 'CTRL+plus'

Hiding Level Deeper C<hiding_level_deeper>

=item 'CTRL+r'

Change Slot Role C<change_slot_role>

=item 'CTRL+s'

Enforce String C<enforce_string>

=item 'CTRL+t'

Change Slot Type C<change_slot_type>

=item 'CTRL+v'

Edit: Paste Subtree C<paste_subtree>

=item 'CTRL+x'

Edit: Cut Subtree C<cut_subtree>

=item 'End'

Move to Last Nest C<move_word_end>

=item 'Home'

Move to First Nest C<move_word_home>

=item 'SHIFT+BackSpace'

Redo Action C<invoke_redo>

=item 'SHIFT+End'

Move to Last Cluster C<move_par_end>

=item 'SHIFT+Home'

Move to First Cluster C<move_par_home>

=back

=head1 SEE ALSO

TrEd Tree Editor L<http://ufal.mff.cuni.cz/~pajas/tred/>

Prague Arabic Dependency Treebank L<http://ufal.mff.cuni.cz/padt/online/>


=head1 AUTHOR

Otakar Smrz, L<http://ufal.mff.cuni.cz/~smrz/>

    eval { 'E<lt>' . ( join '.', qw 'otakar smrz' ) . "\x40" . ( join '.', qw 'mff cuni cz' ) . 'E<gt>' }

Perl is also designed to make the easy jobs not that easy ;)


=head1 COPYRIGHT AND LICENSE

Copyright 2006-2009 by Otakar Smrz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


