=head1 NAME

MorphoTrees - Context for Annotation of Morphology in the TrEd Environment


=head1 REVISION

    $Revision: 730 $       $Date: 2008-10-18 22:48:24 +0200 (Sat, 18 Oct 2008) $


=head1 DESCRIPTION

MorphoTrees were first introduced in L<http://ufal.mff.cuni.cz/padt/docs/2004-nemlar-tred.pdf>.
They have re-appeared in various papers and talks, esp. in the video-recorded lecture on the Prague
Arabic Dependency Treebank, L<http://ufal.mff.cuni.cz/padt/online/2007/01/prague-treebanking-for-everyone-video.html>.

Examples of MorphoTrees include L<http://ufal.mff.cuni.cz/padt/docs/morpho_fhm.gif>,
L<http://ufal.mff.cuni.cz/padt/docs/morpho_AfrAd.gif>, or
L<http://ufal.mff.cuni.cz/padt/docs/morpho_AmA.gif>.

Paragraph annotation trees look like L<http://ufal.mff.cuni.cz/padt/docs/morpho_view.gif>.

For further reference, see the list of MorphoTrees macros and key-bindings in the User-defined menu item in TrEd.

MorphoTrees are closely related to the ElixirFM project, cf. <http://sf.net/projects/elixir-fm/> and
<http://ufal.mff.cuni.cz/~smrz/elixir-thesis.pdf>.




=head1 BINDINGS

=over

=item '1'

Restrict Case Nominative C<restrict_case_nom>

=item '2'

Restrict Case Genitive C<restrict_case_gen>

=item '3'

Restrict Person Third ;) C<restrict_third>

=item '4'

Restrict Case Accusative C<restrict_case_acc>

=item 'A'

Restrict State Absolute C<restrict_state_a>

=item 'BackSpace'

Undo Annotate / Restrict C<invoke_undo>

=item 'C'

Restrict State Complex C<restrict_state_c>

=item 'CTRL+1'

Restrict Person First C<restrict_first>

=item 'CTRL+2'

Restrict Person Second C<restrict_second>

=item 'CTRL+3'

Restrict Person Third C<restrict_third>

=item 'CTRL+ALT+1'

Action: Edit MorphoTrees File C<open_level_first>

=item 'CTRL+ALT+2'

Action: Edit Analytic File C<open_level_second>

=item 'CTRL+ALT+3'

Action: Edit DeepLevels File C<open_level_third>

=item 'CTRL+ALT+equal'

Action: Synchronize Annotations C<synchronize_file>

=item 'CTRL+Down'

Follow Annotation Down C<follow_apply_down>

=item 'CTRL+End'

Move to Last on Level C<move_next_end>

=item 'CTRL+F1'

Level Guide Mode Normal C<level_guide_mode_none>

=item 'CTRL+F2'

Level Guide Mode Strict C<level_guide_mode_fine>

=item 'CTRL+F3'

Level Guide Mode Xtreme C<level_guide_mode_high>

=item 'CTRL+Home'

Move to First on Level C<move_next_home>

=item 'CTRL+Left'

Follow Annotation Left C<follow_apply_left>

=item 'CTRL+Return'

ThisAddress() to Clipboard C<ThisAddressClipBoard>

=item 'CTRL+Right'

Follow Annotation Right C<follow_apply_right>

=item 'CTRL+SHIFT+Down'

Move Down to Fork C<move_to_fork>

=item 'CTRL+SHIFT+Up'

Move Up to Root C<move_to_root>

=item 'CTRL+Up'

Follow Annotation Up C<follow_apply_up>

=item 'CTRL+c'

Restrict Voice Active C<restrict_active>

=item 'CTRL+d'

Restrict Illusory Dual C<restrict_dual>

=item 'CTRL+equal'

Toggle Tree Hide Mode C<tree_hide_mode>

=item 'CTRL+f'

Restrict Illusory Feminine C<restrict_feminine>

=item 'CTRL+m'

Restrict Illusory Masculine C<restrict_masculine>

=item 'CTRL+p'

Restrict Illusory Plural C<restrict_plural>

=item 'CTRL+s'

Restrict Illusory Singular C<restrict_singular>

=item 'CTRL+space'

Annotate as if by Clicking C<annotate_morphology_click>

=item 'CTRL+t'

Restrict Voice Passive C<restrict_passive>

=item 'D'

Restrict Adverb C<restrict_adverb>

=item 'End'

Move to Last Word C<move_word_end>

=item 'Escape'

Remove Induced Restrict C<remove_induced_restrict>

=item 'Home'

Move to First Word C<move_word_home>

=item 'I'

Restrict Verb Indicative C<restrict_indicative>

=item 'J'

Restrict Verb Jussive C<restrict_jussive>

=item 'L'

Restrict State Lifted C<restrict_state_l>

=item 'P'

Restrict Verb Perfect C<restrict_perfect>

=item 'S'

Restrict Verb Subjunctive C<restrict_subjunctive>

=item 'SHIFT+BackSpace'

Redo Annotate / Restrict C<invoke_redo>

=item 'SHIFT+End'

Move to Last Paragraph C<move_par_end>

=item 'SHIFT+Escape'

Remove Inherited Restrict C<remove_inherited_restrict>

=item 'SHIFT+Home'

Move to First Paragraph C<move_par_home>

=item 'SHIFT+Next'

Move to Next Paragraph C<move_to_next_paragraph>

=item 'SHIFT+Prior'

Move to Prev Paragraph C<move_to_prev_paragraph>

=item 'SHIFT+space'

Switch Either Context C<switch_either_context>

=item 'a'

Restrict Adjective C<restrict_adjective>

=item 'c'

Restrict Conjunction C<restrict_conjunction>

=item 'd'

Restrict State Definite C<restrict_state_d>

=item 'exclam'

Edit Annotation Comment C<edit_comment>

=item 'f'

Restrict Particle C<restrict_particle>

=item 'i'

Restrict State Indefinite C<restrict_state_i>

=item 'n'

Restrict Noun C<restrict_noun>

=item 'p'

Restrict Preposition C<restrict_preposition>

=item 'r'

Restrict State Reduced C<restrict_state_r>

=item 's'

Restrict Pronoun C<restrict_pronoun>

=item 'space'

Annotate Morphology C<annotate_morphology>

=item 'v'

Restrict Verb C<restrict_verb>

=item 'z'

Restrict Proper Name C<restrict_proper>

=back

=head1 SEE ALSO

TrEd Tree Editor L<http://ufal.mff.cuni.cz/~pajas/tred/>

Prague Arabic Dependency Treebank L<http://ufal.mff.cuni.cz/padt/online/>


=head1 AUTHOR

Otakar Smrz, L<http://ufal.mff.cuni.cz/~smrz/>

    eval { 'E<lt>' . ( join '.', qw 'otakar smrz' ) . "\x40" . ( join '.', qw 'mff cuni cz' ) . 'E<gt>' }

Perl is also designed to make the easy jobs not that easy ;)


=head1 COPYRIGHT AND LICENSE

Copyright 2004-2008 by Otakar Smrz

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


